### ISSUE TITLE
sfp is not respecting multiple force ignore files

### ISSUE THREAD

**Issue by azlam-abdulsalam** [flxbl-io/sfp#37]
**Describe the bug**
sfp doesnt respect multiple force ignore files when the sfdx-project.json is defined with  ```plugins.sfpowerscripts.ignoreFiles``` parameter in sfdx-project.json 

**To Reproduce**
Use the multiple force ignore feature using plugins.sfpowerscripts, note that this components are not correctly ignored

**Expected behavior**
Need to retain backward compatibility

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: all
 - Version [e.g. CLI Version  eg: 1.6.6] 37.1.1

**Additional context**
The same works with```plugins.sfp.ignoreFiles```

**Comment by domrycz** [comment]
Hey guys, I've recently encountered this bug on validate command. I've changed the structure in sfdx-project.json and now part related to ignore files looks like this:

`"plugins": {
        "sfp": {
            "ignoreFiles": {
                "prepare": "forceignores/.prepare-ignore",
                "validate": "forceignores/.validate-ignore",
                "quickbuild": "forceignores/.quickbuild-ignore",
                "build": "forceignores/.build-ignore"
            }
        }
    }`

The problem is that after I've changed from **plugins.sfpowerscripts.ignoreFiles** to **plugins.sfp.ignoreFiles** it started working for validate and build but it doesn't work for prepare (and the content of _.prepare-ignore_ and _.validate-ignore_ is the same). In [docs](https://docs.flxbl.io/sfp/building-artifacts/controlling-aspects-of-the-build-command/selective-ignoring-of-components-from-being-built) you have examples only for build and validate - could you check if my structure is valid also for prepare?
I'm using **sfp pool prepare** command.

**Comment by azlam-abdulsalam** [comment]
@domrycz  can you confirm for the newer versions

**Comment by azlam-abdulsalam** [comment]
Closing this
